apiVersion: platform.sarige.dev/v1alpha1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: demo-api
    app.kubernetes.io/managed-by: kubernetes-platform
  name: demo-api
spec:
  image: nginx:1.27
  port: 80
  replicas: 2
  host: demo.local
